### ISSUE TITLE
Material Filter Unmount

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/sfm#22]
Issue:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at CountButton (http://localhost:3000/sfm/static/js/main.chunk.js:956:3)
    at div
    at Material (http://localhost:3000/sfm/static/js/main.chunk.js:3784:5)
```

How to recreate:
Make units that are usually not shown with filer non equal 0. When Clicking 0, item is being removed from filtered view and we get the error in console log.

**Comment by jelizarovas** [comment]
After removing longpress, issue does not reappear
